services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  tests_common:
    build:
      context: ./
      target: norm_base
    volumes:
      - .:/usr/src/app
    command: testament category common

  tests_sqlite:
    build:
      context: ./
      target: norm_sqlite
    volumes:
      - .:/usr/src/app
    command: testament category sqlite

  tests_postgres:
    build:
      context: ./
      target: norm_postgres
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: testament category postgres

  docs:
    build:
      context: ./
      target: norm_base
    volumes:
      - .:/usr/src/app
    command: nimble docs

  book:
    build:
      context: ./
      target: norm_base
    volumes:
      - .:/usr/src/app
    command: nimble book

