version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  tests:
    build: .
    image: norm
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: nimble test

  test:
    build: .
    image: norm
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    entrypoint: testament run

  docs:
    build: .
    image: norm
    volumes:
      - .:/usr/src/app
    command: nimble docs

  book:
    build: .
    image: norm
    volumes:
      - .:/usr/src/app
    command: nimble book

