services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  tests_common:
    build:
      context: ./
      target: norm_base
    volumes:
      - ./src:/usr/src/app/src
      - ./tests:/usr/src/app/tests
    command: testament category common

  tests_sqlite:
    build:
      context: ./
      target: norm_sqlite
    volumes:
      - ./src:/usr/src/app/src
      - ./tests:/usr/src/app/tests
    command: testament category sqlite

  tests_postgres:
    build:
      context: ./
      target: norm_postgres
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/src/app/src
      - ./tests:/usr/src/app/tests
    command: testament category postgres

  docs:
    build:
      context: ./
      target: norm_base
    volumes:
      - ./src:/usr/src/app/src
      - ./docs/apidocs:/usr/src/app/docs/apidocs
    command: nimble docs

  book:
    build:
      context: ./
      target: norm_base
    volumes:
      - ./book:/usr/src/app/book
      - ./docs:/usr/src/app/docs
    command: nimble book
