name: Run Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  Tests:
    timeout-minutes: 30

    name: Nim ${{ matrix.nim-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nim-version: ['1.6.18', 'devel']

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: # Needed so we don't need to run in a container
          - 5432:5432

    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}

      - run: nimble install -y nimble && nimble install -y

      - name: Run tests
        run: testament all
        env:
          PGHOST: localhost

  Benchmark:
    timeout-minutes: 30

    name: Nim ${{ matrix.nim-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nim-version: ['1.6.18', 'devel']

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: # Needed so we don't need to run in a container
          - 5432:5432

    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}

      - run: nimble install -y nimble && nimble install -y

      - name: Run benchmark
        run: nimble benchmark 
        env:
          PGHOST: localhost

  Book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Book
        run: docker compose run book
 
  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docs
        run: docker compose run docs

